lint.ignore = [
    "A002",
    "ANN001",
    "ANN002",
    "ANN003",
    "ANN201",
    "B006",
    "BLE001",
    "D100",
    "D104",
    "D205",
    "D401",
    "E501",
    "F821",
    "FBT002",
    "FBT003",
    "FURB101",
    "I001",
    "INT001",
    "PERF401",
    "PLC1901",
    "PLR0912",
    "PLR0913",
    "PLR0914",
    "PLR0915",
    "PLR0917",
    "PLR2004",
    "PLW2901",
    "SIM115",
    "PTH103",
    "PTH107",
    "PTH109",
    "PTH110",
    "PTH112",
    "PTH113",
    "PTH118",
    "PTH119",
    "PTH123",
    "PTH207",
    "PTH208",
    "S101",
    "S113",
    "S404",
    "S603",
    "S604",
    "S605",
]