lint.ignore = [
    "ANN001",
    "ANN201",
    "D100",
    "D104",
    "D205",
    "D401",
    "F821",
    "FBT002",
    "PERF401",
    "PLR0912",
    "PLR0913",
    "PLR0914",
    "PLR0915",
    "PLR0917",
    "SIM115",
    "PTH107",
    "PTH109",
    "PTH112",
    "PTH113",
    "PTH119",
    "PTH123",
    "S404",
    "S605",
]